[project]
name = "commonkads"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "experta>=1.9.4",
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
]
